# -*- coding: utf-8 -*-
"""Team_A_11_Major_Project_Stage_Final_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S08OUTEVkJZh6ncC2LeP3IATc0AfFOsT
"""

# ============================================================
# FINAL ENV SETUP — CLEAN & COMPATIBLE (NO ERRORS)
# Works with Python 3.12 + LaMa + Your Refiner Pipeline
# ============================================================

import subprocess, sys

print("🔧 Installing dependencies (stable setup)...")

# Step 1: Install LaMa FIRST (brings torch automatically)
subprocess.run([
    sys.executable, "-m", "pip", "install",
    "simple-lama-inpainting",
    "-q"
], check=False)

# Step 2: Fix Pillow + NumPy (critical for your pipeline)
subprocess.run([
    sys.executable, "-m", "pip", "install",
    "--upgrade",
    "--force-reinstall",
    "pillow==9.5.0",
    "numpy==1.26.4",
    "-q"
], check=False)

# Step 3: Install remaining required libs
packages = [
    "omegaconf",
    "kornia",
    "lpips",
    "torchmetrics",
    "einops",
    "opencv-python",
    "matplotlib",
    "tqdm"
]

for p in packages:
    subprocess.run([
        sys.executable, "-m", "pip", "install", p, "-q"
    ], check=False)

print("\n✅ Installation complete")
print("⚠️ IMPORTANT: Restart runtime NOW (Runtime → Restart)")

import torch, torchvision, PIL, numpy

print("torch       :", torch.__version__)
print("torchvision :", torchvision.__version__)
print("Pillow      :", PIL.__version__)
print("numpy       :", numpy.__version__)

# ============================================================
# CELL 1 FINAL — Run once, restart runtime, run again
# ============================================================
import subprocess, sys, os

# Install simple-lama FIRST (it will pull bad Pillow)
print("Step 1: Installing simple-lama-inpainting...")
subprocess.run([sys.executable,'-m','pip','install',
                'simple-lama-inpainting','-q'], capture_output=True)

# NOW force Pillow down AFTER simple-lama pulled it up
print("Step 2: Pinning Pillow to 9.5.0...")
subprocess.run([sys.executable,'-m','pip','install',
                'Pillow==9.5.0','--force-reinstall',
                '--no-deps','-q'], capture_output=True)

# Install rest
print("Step 3: Installing other packages...")
for p in ['omegaconf','kornia','lpips','torchmetrics',
          'kagglehub','einops']:
    subprocess.run([sys.executable,'-m','pip','install',p,'-q'],
                   capture_output=True)

print("Step 4: RESTART RUNTIME NOW")
print("        Runtime → Restart Runtime")
print("        Then run CELL 1b below")
print()
print("After restart, paste and run this in a new cell:")
print("""
# ── CELL 1b (paste after restart) ──────────────────────────
import os, warnings, random, cv2
import numpy as np, matplotlib.pyplot as plt
from PIL import Image
from tqdm import tqdm
import torch, torch.nn as nn, torch.nn.functional as F
from torchvision import transforms, models
from torch.utils.data import Dataset, DataLoader
warnings.filterwarnings('ignore')

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
vram   = torch.cuda.get_device_properties(0).total_memory/1e9 if torch.cuda.is_available() else 0
batch_size = 8 if vram >= 10 else 4

BASE = '/content/Dunhuang_LaMa'
for d in ['data/raw_dunhuang',
          'data/train/orig','data/train/damaged','data/train/mask',
          'data/val/orig','data/val/damaged','data/val/mask',
          'results','models']:
    os.makedirs(f'{BASE}/{d}', exist_ok=True)

print(f"Device: {device} | VRAM: {vram:.1f}GB | Batch: {batch_size}")
""")

# ============================================================
# CELL 2: Download Dunhuang + Build Dataset
# Fixed: searches actual kagglehub cache path
# ============================================================

import os, random, glob, cv2, json
import numpy as np
from PIL import Image
from tqdm import tqdm
import matplotlib.pyplot as plt
import subprocess

BASE = '/content/Dunhuang_LaMa'
os.makedirs(f'{BASE}/results', exist_ok=True)
os.makedirs(f'{BASE}/data/train/orig',    exist_ok=True)
os.makedirs(f'{BASE}/data/train/damaged', exist_ok=True)
os.makedirs(f'{BASE}/data/train/mask',    exist_ok=True)
os.makedirs(f'{BASE}/data/val/orig',      exist_ok=True)
os.makedirs(f'{BASE}/data/val/damaged',   exist_ok=True)
os.makedirs(f'{BASE}/data/val/mask',      exist_ok=True)

# ══════════════════════════════════════════════════════════
# STEP 1: FIND IMAGES — search ALL possible locations
# ══════════════════════════════════════════════════════════
print("Step 1: Finding Dunhuang images...")

import kagglehub
path = kagglehub.dataset_download("mrzzzz22/dh-version1")
print(f"Kaggle cache path: {path}")

# Search recursively from cache root
search_roots = [
    path,
    '/root/.cache/kagglehub',
    '/root/.cache/kaggle',
    '/tmp/dh',
    f'{BASE}/data/raw_dunhuang',
]

all_imgs = []
for root in search_roots:
    if os.path.exists(root):
        found = (glob.glob(f'{root}/**/*.png', recursive=True) +
                 glob.glob(f'{root}/**/*.jpg', recursive=True) +
                 glob.glob(f'{root}/**/*.jpeg',recursive=True))
        all_imgs.extend(found)
        if found:
            print(f"  Found {len(found)} in {root}")

# Deduplicate
all_imgs = list(set(all_imgs))
print(f"Total unique images: {len(all_imgs)}")

if len(all_imgs) == 0:
    # Last resort: walk entire filesystem from /root
    print("Searching entire /root for images...")
    for dirpath, dirnames, filenames in os.walk('/root/.cache'):
        for f in filenames:
            if f.lower().endswith(('.png','.jpg','.jpeg')):
                all_imgs.append(os.path.join(dirpath,f))
    print(f"Found after deep search: {len(all_imgs)}")

print(f"\nSample paths:")
for p in all_imgs[:3]:
    print(f"  {p}")

# ══════════════════════════════════════════════════════════
# STEP 2: FILTER GOOD IMAGES
# ══════════════════════════════════════════════════════════
print(f"\nStep 2: Filtering {len(all_imgs)} images...")

def is_good(path):
    try:
        img = np.array(Image.open(path).convert('RGB'))
        h, w = img.shape[:2]
        if h < 200 or w < 200: return False
        b = img.mean()
        if b > 210 or b < 15: return False
        hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)
        if hsv[:,:,1].mean() < 20: return False
        return True
    except: return False

good = [p for p in tqdm(all_imgs, desc='Filter') if is_good(p)]
random.shuffle(good)
print(f"Good images: {len(good)}")

if len(good) == 0:
    raise RuntimeError("No good images found! Check kaggle download above.")

# ══════════════════════════════════════════════════════════
# STEP 3: DETECT REAL DAMAGE
# ══════════════════════════════════════════════════════════
def detect_real_damage(path):
    img  = np.array(Image.open(path).convert('RGB'))
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    hsv  = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)
    H, W = gray.shape
    m_bright = ((gray>185)&(hsv[:,:,1]<55)).astype(np.uint8)*255
    m_dark   = ((gray< 45)&(hsv[:,:,1]<55)).astype(np.uint8)*255
    m = cv2.bitwise_or(m_bright, m_dark)
    k = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(7,7))
    m = cv2.morphologyEx(m, cv2.MORPH_CLOSE, k)
    m = cv2.morphologyEx(m, cv2.MORPH_OPEN,
        cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(3,3)))
    n,labels,stats,_ = cv2.connectedComponentsWithStats(m)
    out = np.zeros_like(m)
    for i in range(1,n):
        if stats[i,cv2.CC_STAT_AREA] >= int(H*W*0.002):
            out[labels==i] = 255
    cov = out.sum()/(H*W*255)*100
    return cov >= 3.0, out, cov

def make_small_damage(h, w):
    mask = np.zeros((h,w), np.uint8)
    for _ in range(random.randint(2,4)):
        x,y = random.randint(0,w), random.randint(0,h)
        for _ in range(random.randint(3,8)):
            angle = random.uniform(0, 2*np.pi)
            l = random.randint(5,20)
            x2=int(np.clip(x+l*np.cos(angle),0,w-1))
            y2=int(np.clip(y+l*np.sin(angle),0,h-1))
            cv2.line(mask,(x,y),(x2,y2),255,random.randint(1,3))
            x,y=x2,y2
    for _ in range(random.randint(5,15)):
        cx,cy=random.randint(5,w-5),random.randint(5,h-5)
        cv2.circle(mask,(cx,cy),random.randint(2,6),255,-1)
    cov = mask.sum()/(h*w*255)
    if cov > 0.05:
        mask=(mask.astype(float)*(0.05/cov)).clip(0,255).astype(np.uint8)
    return mask

def apply_damage(img_np, mask):
    defect = img_np.copy().astype(np.float32)
    ft = random.choices(['plaster','dark','faded'],[0.4,0.4,0.2])[0]
    if ft=='plaster':
        fill=np.clip(random.randint(200,245)+
                     np.random.randint(-15,15,defect.shape),0,255
                     ).astype(np.float32)
    elif ft=='dark':
        fill=np.random.randint(0,30,defect.shape).astype(np.float32)
    else:
        gray=cv2.cvtColor(img_np,cv2.COLOR_RGB2GRAY)
        fill=np.stack([gray]*3,-1).astype(np.float32)*0.6
    bm=cv2.GaussianBlur(mask,(5,5),0)[:,:,None]/255.
    return np.clip((1-bm)*defect+bm*fill,0,255).astype(np.uint8)

# ══════════════════════════════════════════════════════════
# STEP 4: BUILD 500 train + 100 val
# ══════════════════════════════════════════════════════════
print("\nStep 3: Building dataset (500 train + 100 val)...")

TARGET = min(600, len(good))
use    = good[:TARGET]
random.shuffle(use)
split  = int(len(use)*0.83)
splits = {'train': use[:split], 'val': use[split:]}
IMG_SZ = 256
stats  = {'real':0,'synth':0,'skip':0}

def process(paths, split):
    ok=0
    for i,src in enumerate(tqdm(paths,desc=split)):
        try:
            pil    = Image.open(src).convert('RGB').resize(
                (IMG_SZ,IMG_SZ),Image.LANCZOS)
            np_img = np.array(pil)
            name   = f"{i:05d}.png"
            has_r,mask,cov = detect_real_damage(src)
            if has_r:
                mask256=cv2.resize(mask,(IMG_SZ,IMG_SZ),
                                   interpolation=cv2.INTER_NEAREST)
                defect=np_img.copy()
                stats['real']+=1
            else:
                mask256=make_small_damage(IMG_SZ,IMG_SZ)
                defect=apply_damage(np_img,mask256)
                stats['synth']+=1
            Image.fromarray(np_img ).save(f'{BASE}/data/{split}/orig/{name}')
            Image.fromarray(defect ).save(f'{BASE}/data/{split}/damaged/{name}')
            Image.fromarray(mask256).save(f'{BASE}/data/{split}/mask/{name}')
            ok+=1
        except: stats['skip']+=1
    return ok

n_tr = process(splits['train'],'train')
n_va = process(splits['val'],  'val')

print(f"\n{'='*55}")
print(f"Train: {n_tr}  Val: {n_va}")
print(f"Real damage: {stats['real']}  Synthetic: {stats['synth']}  Skip: {stats['skip']}")
print(f"{'='*55}")

# ══════════════════════════════════════════════════════════
# PREVIEW
# ══════════════════════════════════════════════════════════
BG='#0d0a08'; GOLD='#c4924a'; CREAM='#e8d5b0'
orig_files = sorted(glob.glob(f'{BASE}/data/train/orig/*.png'))[:4]
if orig_files:
    fig,axes=plt.subplots(min(4,len(orig_files)),3,
                          figsize=(12,4*min(4,len(orig_files))),
                          facecolor=BG)
    if len(orig_files)==1: axes=[axes]
    fig.suptitle(f'Dataset  train={n_tr}  val={n_va}',
                 fontsize=13,fontweight='bold',color=GOLD)
    for row,op in enumerate(orig_files[:4]):
        n=os.path.basename(op)
        ori=np.array(Image.open(f'{BASE}/data/train/orig/{n}'))
        dam=np.array(Image.open(f'{BASE}/data/train/damaged/{n}'))
        msk=np.array(Image.open(f'{BASE}/data/train/mask/{n}'))
        cov=msk.mean()/255*100
        for col,(arr,title) in enumerate(zip(
            [ori,dam,msk],['Original',f'Damaged({cov:.0f}%)','Mask'])):
            ax=axes[row][col] if len(orig_files)>1 else axes[col]
            ax.imshow(arr,cmap='hot' if col==2 else None)
            ax.set_title(title,fontsize=9,color=CREAM,pad=6)
            ax.axis('off'); ax.set_facecolor(BG)
    plt.tight_layout()
    plt.savefig(f'{BASE}/results/dataset_preview.png',dpi=100,facecolor=BG)
    plt.show()

# ============================================================
# AUTO SAVE + LOAD DATASET (ONE CELL — FULLY REUSABLE)
# ============================================================

import os, shutil
from google.colab import drive

drive.mount('/content/drive')

BASE       = '/content/Dunhuang_LaMa'
LOCAL_DATA = f'{BASE}/data'
DRIVE_DATA = '/content/drive/MyDrive/Dunhuang_Dataset'

# ============================================================
# STEP 1: CHECK IF DATASET EXISTS IN DRIVE
# ============================================================

if os.path.exists(DRIVE_DATA):
    print("✅ Dataset found in Drive → loading...")

    # Remove old local copy if exists
    if os.path.exists(LOCAL_DATA):
        shutil.rmtree(LOCAL_DATA)

    # Copy dataset from Drive to runtime
    shutil.copytree(DRIVE_DATA, LOCAL_DATA)

    print("🚀 Dataset loaded from Drive — ready to use")

# ============================================================
# STEP 2: IF NOT EXISTS → EXPECT USER TO RUN DATASET CREATION
# ============================================================

else:
    print("⚠️ Dataset NOT found in Drive")
    print("👉 Run your dataset creation cell (CELL 2) first")
    print("👉 Then re-run this cell to save it")

    # OPTIONAL: Auto-save if dataset already exists locally
    if os.path.exists(LOCAL_DATA):
        print("📦 Saving existing dataset to Drive...")

        shutil.copytree(LOCAL_DATA, DRIVE_DATA)

        print(f"✅ Dataset saved to Drive: {DRIVE_DATA}")

# ============================================================
# CELL 3: LaMa + DunhuangRefiner — Residual Learning
# Refiner learns CORRECTION on top of LaMa, not full image
# ============================================================

import torch, torch.nn as nn, torch.nn.functional as F
import numpy as np
from PIL import Image
import torchvision.transforms as T

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# ── Load LaMa ─────────────────────────────────────────────
print("Loading pretrained LaMa...")
from simple_lama_inpainting import SimpleLama
simple_lama = SimpleLama()
lama_model  = simple_lama.model.to(device)
lama_model.eval()
for p in lama_model.parameters():
    p.requires_grad = False
print(f"✅ LaMa frozen: {sum(p.numel() for p in lama_model.parameters())/1e6:.1f}M")

# ── Gated Conv block ──────────────────────────────────────
class GatedConv(nn.Module):
    def __init__(self, in_ch, out_ch, k=3, s=1, d=1):
        super().__init__()
        p = d*(k//2)
        self.conv  = nn.Conv2d(in_ch, out_ch, k, s, p, dilation=d)
        self.gate  = nn.Conv2d(in_ch, out_ch, k, s, p, dilation=d)
        self.bn    = nn.BatchNorm2d(out_ch)
    def forward(self, x):
        return self.bn(self.conv(x) * torch.sigmoid(self.gate(x)))

# ── DunhuangRefiner v2 — Residual Correction ──────────────
class DunhuangRefiner(nn.Module):
    """
    Input : lama_out (3) + orig_img (3) + mask (1) = 7ch
    Output: lama_out + learned_correction * hole_mask
    Residual design: refiner predicts DIFFERENCE from LaMa
    This forces it to learn what LaMa got wrong, not repeat it
    """
    def __init__(self):
        super().__init__()
        # Encoder — gated convs for hole-awareness
        self.e1 = GatedConv(7,  64)        # [B,64,H,W]
        self.e2 = GatedConv(64, 128, s=2)  # [B,128,H/2,W/2]
        self.e3 = GatedConv(128,256, s=2)  # [B,256,H/4,W/4]
        self.e4 = GatedConv(256,256, s=2)  # [B,256,H/8,W/8]

        # Dilated bottleneck — large receptive field for patterns
        self.d1 = GatedConv(256,256, d=2)
        self.d2 = GatedConv(256,256, d=4)
        self.d3 = GatedConv(256,256, d=8)
        self.d4 = GatedConv(256,256, d=16)
        self.dfuse = nn.Conv2d(256*4, 256, 1)

        # Decoder with skip connections
        self.up3  = nn.Upsample(scale_factor=2,mode='bilinear',align_corners=False)
        self.dec3 = GatedConv(256+256, 256)

        self.up2  = nn.Upsample(scale_factor=2,mode='bilinear',align_corners=False)
        self.dec2 = GatedConv(256+128, 128)

        self.up1  = nn.Upsample(scale_factor=2,mode='bilinear',align_corners=False)
        self.dec1 = GatedConv(128+64, 64)

        # Residual correction head — outputs [-1,1] correction
        self.corr = nn.Sequential(
            nn.Conv2d(64, 32, 3, padding=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(32, 3,  3, padding=1),
            nn.Tanh()
        )

        # Confidence head — how much to trust correction vs LaMa
        self.conf = nn.Sequential(
            nn.Conv2d(64, 32, 3, padding=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(32, 1,  3, padding=1),
            nn.Sigmoid()
        )

    def forward(self, lama_out, orig_img, mask):
        # mask: 1=intact 0=damaged
        hole = 1 - mask
        x  = torch.cat([lama_out, orig_img, mask], dim=1)

        e1 = self.e1(x)
        e2 = self.e2(e1)
        e3 = self.e3(e2)
        e4 = self.e4(e3)

        # Dilated bottleneck
        b = torch.cat([self.d1(e4),self.d2(e4),
                       self.d3(e4),self.d4(e4)], dim=1)
        b = F.relu(self.dfuse(b), inplace=True)

        # Decoder
        d3 = self.dec3(torch.cat([self.up3(b),  e3], dim=1))
        d2 = self.dec2(torch.cat([self.up2(d3), e2], dim=1))
        d1 = self.dec1(torch.cat([self.up1(d2), e1], dim=1))

        corr = self.corr(d1)   # residual correction [-1,1]
        conf = self.conf(d1)   # confidence [0,1]

        # Apply correction only to hole regions
        # lama_out is our base — we add a confident correction
        corrected = (lama_out + corr * 0.5).clamp(-1, 1)
        blended   = conf * corrected + (1-conf) * lama_out

        # Composite: intact pixels stay original
        return orig_img * mask + blended * hole

refiner = DunhuangRefiner().to(device)
print(f"✅ Refiner v2 (residual): "
      f"{sum(p.numel() for p in refiner.parameters())/1e6:.2f}M params")

# ── LaMa batch helper ─────────────────────────────────────
img_tf = T.Compose([T.ToTensor(), T.Normalize([0.5]*3,[0.5]*3)])
def unnorm(t): return (t*0.5+0.5).clamp(0,1)

def lama_inpaint_batch(img_t, mask_t):
    results = []
    for i in range(img_t.shape[0]):
        img_pil  = Image.fromarray(
            (unnorm(img_t[i]).cpu().permute(1,2,0).numpy()*255
             ).astype(np.uint8))
        mask_np  = ((1-mask_t[i,0]).cpu().numpy()*255).astype(np.uint8)
        mask_pil = Image.fromarray(mask_np).convert('L')
        out_pil  = simple_lama(img_pil, mask_pil)
        results.append(img_tf(out_pil).unsqueeze(0))
    return torch.cat(results, dim=0).to(device)

# ── Verify ────────────────────────────────────────────────
print("\nVerifying forward pass...")
with torch.no_grad():
    di = torch.randn(1,3,256,256).to(device)
    dm = torch.ones(1,1,256,256).to(device)
    dm[:,:,80:160,80:160] = 0
    lo = lama_inpaint_batch(di, dm)
    print(f"  LaMa   : {lo.shape} range=[{lo.min():.2f},{lo.max():.2f}] ✅")
    ro = refiner(lo, di, dm)
    print(f"  Refiner: {ro.shape} range=[{ro.min():.2f},{ro.max():.2f}] ✅")
    # Verify refiner output DIFFERS from LaMa (residual working)
    diff = (ro - lo).abs().mean().item()
    print(f"  Refiner vs LaMa diff: {diff:.4f} "
          f"{'✅ learning correction' if diff > 0.001 else '❌ too similar'}")
    del di, dm, lo, ro
    torch.cuda.empty_cache()

# ============================================================
# CELL 4: Training — Hole-focused + Edge + Freq losses
# LaMa frozen, Refiner learns residual correction
# ============================================================

import os, time, shutil
import numpy as np
import torch, torch.nn as nn, torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from PIL import Image
from tqdm import tqdm
import matplotlib.pyplot as plt
from datetime import datetime
from google.colab import drive

BASE   = '/content/Dunhuang_LaMa'
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
DATE   = datetime.now().strftime('%Y%m%d')

drive.mount('/content/drive')
DRIVE_DIR = '/content/drive/MyDrive/DunhuangLaMa_Models'
os.makedirs(DRIVE_DIR, exist_ok=True)
os.makedirs(f'{BASE}/models', exist_ok=True)   # ← ADD THIS LINE
os.makedirs(f'{BASE}/results', exist_ok=True)  # ← ADD THIS TOO
print(f"✅ Drive ready")

# ══════════════════════════════════════════════════════════
# DATASET — larger damage masks for harder training
# ══════════════════════════════════════════════════════════
class MuralDataset(Dataset):
    def __init__(self, split='train'):
        self.orig_dir = f'{BASE}/data/{split}/orig'
        self.dam_dir  = f'{BASE}/data/{split}/damaged'
        self.msk_dir  = f'{BASE}/data/{split}/mask'
        self.names    = sorted(os.listdir(self.orig_dir))
        self.tf = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize([0.5]*3,[0.5]*3)
        ])
    def __len__(self): return len(self.names)
    def __getitem__(self, idx):
        n    = self.names[idx]
        orig = Image.open(f'{self.orig_dir}/{n}').convert('RGB')
        dam  = Image.open(f'{self.dam_dir}/{n}').convert('RGB')
        msk  = Image.open(f'{self.msk_dir}/{n}').convert('L')
        import random
        if random.random()>0.5:
            orig=transforms.functional.hflip(orig)
            dam =transforms.functional.hflip(dam)
            msk =transforms.functional.hflip(msk)
        orig_t = self.tf(orig)
        dam_t  = self.tf(dam)
        # mask: 1=intact  0=damaged
        msk_t  = 1.0-(transforms.ToTensor()(msk)>0.5).float()
        return dam_t, msk_t, orig_t

BATCH    = 6
train_ds = MuralDataset('train')
val_ds   = MuralDataset('val')
train_dl = DataLoader(train_ds, batch_size=BATCH, shuffle=True,
                      num_workers=2, pin_memory=True, drop_last=True)
val_dl   = DataLoader(val_ds,   batch_size=BATCH, shuffle=False,
                      num_workers=2, pin_memory=True)
print(f"Train:{len(train_ds)} | Val:{len(val_ds)} | Batch:{BATCH}")

# ══════════════════════════════════════════════════════════
# LOSSES
# ══════════════════════════════════════════════════════════
class VGGPerceptual(nn.Module):
    def __init__(self):
        super().__init__()
        vgg = models.vgg16(weights=models.VGG16_Weights.DEFAULT).features
        self.blocks = nn.ModuleList([
            nn.Sequential(*vgg[:4]),
            nn.Sequential(*vgg[4:9]),
            nn.Sequential(*vgg[9:16]),
            nn.Sequential(*vgg[16:23]),
        ])
        for p in self.parameters(): p.requires_grad=False
    def forward(self, x):
        feats=[]; cur=x
        for b in self.blocks: cur=b(cur); feats.append(cur)
        return feats

vgg_loss = VGGPerceptual().to(device)

# Sobel edge loss — critical for pattern recovery
def edge_loss(pred, target):
    def sobel(t):
        kx = torch.tensor([[-1,0,1],[-2,0,2],[-1,0,1]],
                           dtype=torch.float32,device=t.device
                           ).view(1,1,3,3).repeat(3,1,1,1)
        ky = torch.tensor([[-1,-2,-1],[0,0,0],[1,2,1]],
                           dtype=torch.float32,device=t.device
                           ).view(1,1,3,3).repeat(3,1,1,1)
        ex = F.conv2d(t, kx, padding=1, groups=3)
        ey = F.conv2d(t, ky, padding=1, groups=3)
        return torch.sqrt(ex**2+ey**2+1e-6)
    return F.l1_loss(sobel(pred), sobel(target))

# FFT frequency loss — recovers fine texture patterns
def freq_loss(pred, target):
    fp = torch.fft.rfft2(pred,  norm='ortho')
    ft = torch.fft.rfft2(target,norm='ortho')
    return F.l1_loss(fp.real,ft.real) + F.l1_loss(fp.imag,ft.imag)

def gram(f):
    b,c,h,w=f.shape; f=f.view(b,c,-1)
    return torch.bmm(f,f.transpose(1,2))/(c*h*w)

def unnorm(t): return (t*0.5+0.5).clamp(0,1)

def compute_loss(pred, target, mask, lama_ref):
    hole   = 1 - mask
    n_hole = hole.sum().clamp(min=1)
    n_valid= mask.sum().clamp(min=1)

    # ── L1 losses ──
    # Valid region (intact) — light penalty
    l_valid  = (F.l1_loss(pred*mask, target*mask, reduction='sum')
                / n_valid) * 1.0

    # Hole region — HEAVY penalty, this is where restoration happens
    l_hole   = (F.l1_loss(pred*hole, target*hole, reduction='sum')
                / n_hole) * 10.0

    # Residual vs LaMa — push refiner to actually CHANGE LaMa output
    # penalize if refiner just copies LaMa in hole regions
    l_residual = (F.l1_loss((pred - lama_ref)*hole,
                             (target - lama_ref)*hole,
                             reduction='sum') / n_hole) * 4.0

    # ── Perceptual ──
    fp = vgg_loss(unnorm(pred).float())
    ft = vgg_loss(unnorm(target).float())
    l_perc = sum(F.l1_loss(a,b) for a,b in zip(fp,ft)) * 0.1

    # ── Style (Gram) — pattern texture recovery ──
    l_style = sum(F.l1_loss(gram(a),gram(b))
                  for a,b in zip(fp,ft)) * 80.0

    # ── Edge loss — sharp pattern boundaries ──
    l_edge = edge_loss(unnorm(pred).float(),
                       unnorm(target).float()) * 2.0

    # ── Frequency loss — fine Dunhuang patterns ──
    l_freq = freq_loss(pred, target) * 0.5

    total = (l_valid + l_hole + l_residual +
             l_perc + l_style + l_edge + l_freq)

    return total, {
        'valid':l_valid.item(),'hole':l_hole.item(),
        'resid':l_residual.item(),'perc':l_perc.item(),
        'style':l_style.item(),'edge':l_edge.item(),
        'freq':l_freq.item()
    }

# ══════════════════════════════════════════════════════════
# OPTIMISER
# ══════════════════════════════════════════════════════════
EPOCHS = 20   # more epochs — residual learning needs time
LR     = 3e-4

opt = torch.optim.AdamW(refiner.parameters(),
                         lr=LR, betas=(0.9,0.999), weight_decay=1e-4)
sch = torch.optim.lr_scheduler.OneCycleLR(
        opt, max_lr=LR,
        steps_per_epoch=len(train_dl),
        epochs=EPOCHS, pct_start=0.1)

# ══════════════════════════════════════════════════════════
# VISUALISE — shows LaMa vs Refined diff clearly
# ══════════════════════════════════════════════════════════
def visualise(epoch):
    refiner.eval()
    db,mb,ob = next(iter(val_dl))
    db,mb,ob = db.to(device),mb.to(device),ob.to(device)
    with torch.no_grad():
        lb  = lama_inpaint_batch(db, mb)
        out = refiner(lb, db, mb)
        # Difference map — amplified 3x so small changes visible
        diff = ((out - lb).abs() * 3).clamp(0,1)

    n   = min(3, db.shape[0])
    BG='#0d0a08'; GOLD='#c4924a'; CREAM='#e8d5b0'
    fig = plt.figure(figsize=(20,n*4), facecolor=BG)
    titles=['Damaged','LaMa','Refined','GT','Diff(×3)']
    colors=['#cc4444','#8888ff','#c4924a','#44aa44','#ff88ff']
    fig.suptitle(
        f'Epoch {epoch} — Damaged | LaMa | Refined | GT | Diff(Refined-LaMa)×3',
        color=GOLD, fontsize=11, fontweight='bold')
    srcs = [db, lb, out, ob, diff]
    for row in range(n):
        for col,(src,clr) in enumerate(zip(srcs,colors)):
            ax = fig.add_subplot(n,5,row*5+col+1)
            arr= unnorm(src[row]).cpu().permute(1,2,0).numpy()
            ax.imshow(arr); ax.axis('off')
            if row==0:
                ax.set_title(titles[col],fontsize=8,
                             color=clr,pad=4)
            ax.set_facecolor(BG)
            for s in ax.spines.values():
                s.set_edgecolor(clr)
                s.set_linewidth(2.5 if col==2 else 1)
    plt.tight_layout()
    plt.savefig(f'{BASE}/results/epoch_{epoch:03d}.png',
                dpi=90, facecolor=BG)
    plt.show(); plt.close()
    refiner.train()

# ══════════════════════════════════════════════════════════
# SAVE
# ══════════════════════════════════════════════════════════
best_val = float('inf')

def save(epoch, val_loss):
    global best_val
    path = f'{BASE}/models/refiner_{DATE}_ep{epoch}.pth'
    torch.save({'epoch':epoch,'val_loss':val_loss,
                'state_dict':refiner.state_dict()}, path)
    shutil.copy(path, f'{DRIVE_DIR}/refiner_{DATE}_ep{epoch}.pth')
    if val_loss < best_val:
        best_val = val_loss
        shutil.copy(path, f'{BASE}/models/refiner_{DATE}_best.pth')
        shutil.copy(path, f'{DRIVE_DIR}/refiner_{DATE}_best.pth')
        print(f"  ✨ New best: {val_loss:.4f}")

# ══════════════════════════════════════════════════════════
# TRAINING LOOP
# ══════════════════════════════════════════════════════════
print(f"\n{'='*65}")
print(f"Residual refiner — Losses: L1-hole×10 + Residual×4 + "
      f"Edge×2 + Freq + Style + Perceptual")
print(f"Epochs={EPOCHS} | Batch={BATCH} | LR={LR} | OneCycleLR")
print(f"{'='*65}\n")

history = {'train':[], 'val':[], 'hole':[], 'edge':[]}
t0 = time.time()

for epoch in range(1, EPOCHS+1):
    # ── Train ──
    refiner.train()
    tr_losses=[]; hole_losses=[]; edge_losses=[]
    pbar = tqdm(train_dl, desc=f"Ep{epoch}/{EPOCHS}", ncols=95)

    for db,mb,ob in pbar:
        db,mb,ob = db.to(device),mb.to(device),ob.to(device)
        with torch.no_grad():
            lb = lama_inpaint_batch(db, mb)

        out = refiner(lb, db, mb)
        loss, comp = compute_loss(out, ob, mb, lb)

        if torch.isnan(loss): continue

        opt.zero_grad()
        loss.backward()
        nn.utils.clip_grad_norm_(refiner.parameters(), 1.0)
        opt.step()
        sch.step()

        tr_losses.append(loss.item())
        hole_losses.append(comp['hole'])
        edge_losses.append(comp['edge'])
        pbar.set_postfix({
            'tot':f"{loss.item():.3f}",
            'hole':f"{comp['hole']:.3f}",
            'edge':f"{comp['edge']:.3f}"
        })
        del db,mb,ob,lb,out

    # ── Val ──
    refiner.eval()
    va_losses=[]
    with torch.no_grad():
        for db,mb,ob in val_dl:
            db,mb,ob = db.to(device),mb.to(device),ob.to(device)
            lb  = lama_inpaint_batch(db, mb)
            out = refiner(lb, db, mb)
            vl,_ = compute_loss(out, ob, mb, lb)
            if not torch.isnan(vl):
                va_losses.append(vl.item())
            del db,mb,ob,lb,out
    torch.cuda.empty_cache()

    tr_m = np.mean(tr_losses)  if tr_losses  else float('nan')
    va_m = np.mean(va_losses)  if va_losses  else float('nan')
    h_m  = np.mean(hole_losses)if hole_losses else float('nan')
    e_m  = np.mean(edge_losses)if edge_losses else float('nan')
    elapsed = (time.time()-t0)/60
    eta     = elapsed/epoch*(EPOCHS-epoch)

    history['train'].append(tr_m)
    history['val'].append(va_m)
    history['hole'].append(h_m)
    history['edge'].append(e_m)

    print(f"Ep{epoch:2d}/{EPOCHS}  "
          f"train:{tr_m:.3f}  val:{va_m:.3f}  "
          f"hole:{h_m:.3f}  edge:{e_m:.3f}  "
          f"[{elapsed:.0f}m ~{eta:.0f}m left]")

    if not np.isnan(va_m):
        save(epoch, va_m)

    if epoch % 2 == 0 or epoch == EPOCHS:
        visualise(epoch)

# ── Loss curve ──
BG='#0d0a08'; GOLD='#c4924a'; CREAM='#e8d5b0'
fig,axes = plt.subplots(1,2,figsize=(14,4),facecolor=BG)
for ax in axes: ax.set_facecolor(BG)
axes[0].plot(history['train'],color='#c4924a',label='Train',lw=2)
axes[0].plot(history['val'],  color='#44aa44',label='Val',  lw=2,ls='--')
axes[0].set_title('Total Loss',color=GOLD)
axes[1].plot(history['hole'],color='#cc4444',label='Hole',lw=2)
axes[1].plot(history['edge'],color='#8888ff',label='Edge',lw=2)
axes[1].set_title('Hole + Edge Loss',color=GOLD)
for ax in axes:
    ax.legend(labelcolor=CREAM,facecolor='#1a120a')
    ax.tick_params(colors=CREAM)
    for s in ax.spines.values(): s.set_edgecolor(GOLD)
plt.tight_layout()
plt.savefig(f'{BASE}/results/training_curve.png',dpi=100,facecolor=BG)
plt.show()

print(f"\n✅ Done in {(time.time()-t0)/60:.0f}min | Best val: {best_val:.4f}")
print(f"   Saved to: {DRIVE_DIR}")
print("Say OK for Cell 5")



# ============================================================
# CELL 5b-LOAD: Load ALL models from Drive vault
# ============================================================

import torch, torch.nn as nn, os
import torch.nn.functional as F
import torchvision.models as tvm
import torchvision.transforms as T
from google.colab import drive

drive.mount('/content/drive')

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
BASE  = '/content/Dunhuang_LaMa'
VAULT = '/content/drive/MyDrive/Dunhuang_AllModels'

if not os.path.exists(VAULT):
    raise RuntimeError(f"Vault not found: {VAULT}\nRun CELL 5b-UPLOAD first.")

print(f"📁 Vault contents:")
vault_files = os.listdir(VAULT)
for f in sorted(vault_files):
    size = os.path.getsize(f'{VAULT}/{f}')/1e6
    print(f"  {f}  ({size:.1f} MB)")

# ══════════════════════════════════════════════════════════
# ARCHITECTURES
# ══════════════════════════════════════════════════════════

class CBAM(nn.Module):
    def __init__(self,c,r=16):
        super().__init__()
        self.ca=nn.Sequential(
            nn.AdaptiveAvgPool2d(1),nn.Flatten(),
            nn.Linear(c,c//r),nn.ReLU(),nn.Linear(c//r,c),nn.Sigmoid())
        self.sa=nn.Sequential(nn.Conv2d(2,1,7,padding=3),nn.Sigmoid())
    def forward(self,x):
        w=self.ca(x).view(x.shape[0],x.shape[1],1,1); x=x*w
        m=torch.cat([x.mean(1,keepdim=True),x.max(1,keepdim=True)[0]],1)
        return x*self.sa(m)

class AttGate(nn.Module):
    def __init__(self,g,x,i=128):
        super().__init__()
        self.wg=nn.Conv2d(g,i,1); self.wx=nn.Conv2d(x,i,1)
        self.psi=nn.Sequential(nn.Conv2d(i,1,1),nn.Sigmoid())
    def forward(self,g,x):
        wg = self.wg(g)
        wx = self.wx(x)
        if wg.shape != wx.shape:
            wg = F.interpolate(wg, wx.shape[2:],
                               mode='bilinear', align_corners=False)
        return x * self.psi(F.relu(wg + wx, True))

class GCB(nn.Module):
    def __init__(self,i,o,k=3,s=1,p=1,d=1):
        super().__init__()
        self.c=nn.Conv2d(i,o,k,s,p,dilation=d)
        self.g=nn.Conv2d(i,o,k,s,p,dilation=d)
        self.bn=nn.BatchNorm2d(o)
    def forward(self,x):
        return F.relu(self.bn(self.c(x)*torch.sigmoid(self.g(x))),True)

class RestorationNet(nn.Module):
    def __init__(self):
        super().__init__()
        enc=tvm.resnet34(weights=None)
        self.e0=nn.Sequential(enc.conv1,enc.bn1,enc.relu)
        self.pool=enc.maxpool
        self.e1=enc.layer1; self.e2=enc.layer2
        self.e3=enc.layer3; self.e4=enc.layer4
        self.mid=nn.Sequential(
            GCB(512,512,3,1,2,2),GCB(512,512,3,1,4,4),
            GCB(512,512,3,1,8,8),GCB(512,512,3,1,16,16))
        def up(ic,sc,oc):
            return nn.ModuleDict({'att':AttGate(ic,sc),'cbam':CBAM(sc),
                'up':nn.ConvTranspose2d(ic,oc,4,2,1),'gate':GCB(oc+sc,oc)})
        self.u4=up(512,256,256); self.u3=up(256,128,128)
        self.u2=up(128,64,64);   self.u1=up(64,64,64)
        self.out=nn.Sequential(nn.Conv2d(64,3,3,1,1),nn.Tanh())
    def _up(self,blk,g,x):
        x2=blk['cbam'](blk['att'](g,x))
        g2=blk['up'](g)
        if g2.shape!=x2.shape:
            g2=F.interpolate(g2,x2.shape[2:],mode='bilinear',align_corners=False)
        return blk['gate'](torch.cat([g2,x2],1))
    def forward(self,x,mask):
        xi=x*mask
        e0=self.e0(xi); ep=self.pool(e0)
        e1=self.e1(ep); e2=self.e2(e1)
        e3=self.e3(e2); e4=self.e4(e3)
        m=sum(self.mid[i](e4) for i in range(4))
        d=self._up(self.u4,m,e3); d=self._up(self.u3,d,e2)
        d=self._up(self.u2,d,e1); d=self._up(self.u1,d,e0)
        if d.shape!=xi.shape:
            d=F.interpolate(d,xi.shape[2:],mode='bilinear',align_corners=False)
        return xi*mask+self.out(d)*(1-mask)

class RefinementNet(nn.Module):
    def __init__(self):
        super().__init__()
        def gc(i,o,k=4,s=2,p=1,d=1):
            return nn.ModuleDict({'c':nn.Conv2d(i,o,k,s,p,dilation=d),
                'g':nn.Conv2d(i,o,k,s,p,dilation=d),'n':nn.InstanceNorm2d(o)})
        self.e1=gc(7,64);    self.e2=gc(64,128)
        self.e3=gc(128,256); self.e4=gc(256,512)
        # ── FIX: input must be 512 (e4 output) ───────────
        self.d1=gc(512,512,3,1,2,2); self.d2=gc(512,512,3,1,4,4)
        self.d3=gc(512,512,3,1,8,8)
        def up(i,o):
            return nn.Sequential(nn.ConvTranspose2d(i,o,4,2,1),
                                  nn.InstanceNorm2d(o),nn.ReLU(True))
        self.u1=up(512,256); self.u2=up(256+256,128)
        self.u3=up(128+128,64); self.u4=up(64+64,32)
        self.out=nn.Sequential(nn.Conv2d(32,3,3,1,1),nn.Tanh())
    def _a(self,m,x):
        return F.leaky_relu(m['n'](m['c'](x)*torch.sigmoid(m['g'](x))),0.2,True)
    def forward(self,coarse,orig,mask):
        x=torch.cat([coarse,orig,mask],1)
        e1=self._a(self.e1,x); e2=self._a(self.e2,e1)
        e3=self._a(self.e3,e2); e4=self._a(self.e4,e3)
        b=e4
        for dl in [self.d1,self.d2,self.d3]:
            b=F.leaky_relu(dl['n'](dl['c'](b)*torch.sigmoid(dl['g'](b))),0.2,True)
        d=self.u1(b)
        if d.shape[2:]!=e3.shape[2:]: d=F.interpolate(d,e3.shape[2:])
        d=self.u2(torch.cat([d,e3],1))
        if d.shape[2:]!=e2.shape[2:]: d=F.interpolate(d,e2.shape[2:])
        d=self.u3(torch.cat([d,e2],1))
        if d.shape[2:]!=e1.shape[2:]: d=F.interpolate(d,e1.shape[2:])
        d=self.u4(torch.cat([d,e1],1))
        if d.shape[2:]!=orig.shape[2:]: d=F.interpolate(d,orig.shape[2:])
        return self.out(d)

try:
    _ = DunhuangRefiner
    print("  DunhuangRefiner already defined from Cell 3 ✅")
except NameError:
    class GatedConv(nn.Module):
        def __init__(self,in_ch,out_ch,k=3,s=1,d=1):
            super().__init__()
            p=d*(k//2)
            self.conv=nn.Conv2d(in_ch,out_ch,k,s,p,dilation=d)
            self.gate=nn.Conv2d(in_ch,out_ch,k,s,p,dilation=d)
            self.bn=nn.BatchNorm2d(out_ch)
        def forward(self,x):
            return self.bn(self.conv(x)*torch.sigmoid(self.gate(x)))

    class DunhuangRefiner(nn.Module):
        def __init__(self):
            super().__init__()
            self.e1=GatedConv(7,64);    self.e2=GatedConv(64,128,s=2)
            self.e3=GatedConv(128,256,s=2); self.e4=GatedConv(256,256,s=2)
            self.d1=GatedConv(256,256,d=2); self.d2=GatedConv(256,256,d=4)
            self.d3=GatedConv(256,256,d=8); self.d4=GatedConv(256,256,d=16)
            self.dfuse=nn.Conv2d(256*4,256,1)
            self.up3=nn.Upsample(scale_factor=2,mode='bilinear',align_corners=False)
            self.dec3=GatedConv(256+256,256)
            self.up2=nn.Upsample(scale_factor=2,mode='bilinear',align_corners=False)
            self.dec2=GatedConv(256+128,128)
            self.up1=nn.Upsample(scale_factor=2,mode='bilinear',align_corners=False)
            self.dec1=GatedConv(128+64,64)
            self.corr=nn.Sequential(
                nn.Conv2d(64,32,3,padding=1),nn.ReLU(True),
                nn.Conv2d(32,3,3,padding=1),nn.Tanh())
            self.conf=nn.Sequential(
                nn.Conv2d(64,32,3,padding=1),nn.ReLU(True),
                nn.Conv2d(32,1,3,padding=1),nn.Sigmoid())
        def forward(self,lama_out,orig_img,mask):
            hole=1-mask
            x=torch.cat([lama_out,orig_img,mask],dim=1)
            e1=self.e1(x); e2=self.e2(e1)
            e3=self.e3(e2); e4=self.e4(e3)
            b=torch.cat([self.d1(e4),self.d2(e4),
                         self.d3(e4),self.d4(e4)],dim=1)
            b=F.relu(self.dfuse(b),True)
            d3=self.dec3(torch.cat([self.up3(b),e3],dim=1))
            d2=self.dec2(torch.cat([self.up2(d3),e2],dim=1))
            d1=self.dec1(torch.cat([self.up1(d2),e1],dim=1))
            corr=self.corr(d1); conf=self.conf(d1)
            corrected=(lama_out+corr*0.5).clamp(-1,1)
            blended=conf*corrected+(1-conf)*lama_out
            return orig_img*mask+blended*hole

# ══════════════════════════════════════════════════════════
# LOAD ALL MODELS FROM VAULT
# ══════════════════════════════════════════════════════════
print(f"\n{'='*55}")
print("Loading all models from vault...")
print('='*55)

def load_model(model, path, name):
    if not os.path.exists(path):
        print(f"  ⚠️  {name}: not found — {os.path.basename(path)}")
        return False
    try:
        ck = torch.load(path, map_location=device, weights_only=False)
        sd = ck.get('state_dict', ck)
        model.load_state_dict(sd, strict=False)
        model.eval()
        for p in model.parameters(): p.requires_grad=False
        params = sum(p.numel() for p in model.parameters())/1e6
        ep = ck.get('epoch','?')
        print(f"  ✅ {name:<25} {params:.1f}M  ep={ep}")
        return True
    except Exception as e:
        print(f"  ❌ {name}: {e}")
        return False

def find_best_refiner():
    cands = sorted(
        [f for f in vault_files
         if 'refiner' in f.lower()
         and 'dunhuang' not in f.lower()
         and '20260307' not in f
         and f.endswith('.pth')],
        reverse=True)
    best = ([f for f in cands if 'best' in f] +
            [f for f in cands if 'best' not in f])
    return best[0] if best else None

gen_best = RestorationNet().to(device)
gen_ep60 = RestorationNet().to(device)
ref_net  = RefinementNet().to(device)
old_dun  = DunhuangRefiner().to(device)
new_ref  = DunhuangRefiner().to(device)

loaded = {}
loaded['gen_best'] = load_model(gen_best,
    f'{VAULT}/generator_best.pth',        'RestorationNet-best')
loaded['gen_ep60'] = load_model(gen_ep60,
    f'{VAULT}/generator_ep60.pth',        'RestorationNet-ep60')
loaded['ref_net']  = load_model(ref_net,
    f'{VAULT}/refiner_ep60.pth',           'RefinementNet')
loaded['old_dun']  = load_model(old_dun,
    f'{VAULT}/refiner_20260307_best.pth',  'OldDunhuangRefiner')

best_new = find_best_refiner()
if best_new:
    loaded['new_ref'] = load_model(new_ref,
        f'{VAULT}/{best_new}', 'NewDunhuangRefiner')
    refiner = new_ref
else:
    print("  ⚠️  No new refiner found in vault")

# ══════════════════════════════════════════════════════════
# ENSEMBLE FORWARD
# ══════════════════════════════════════════════════════════
img_tf = T.Compose([T.ToTensor(), T.Normalize([0.5]*3,[0.5]*3)])
def unnorm(t): return (t*0.5+0.5).clamp(0,1)

def ensemble_restore(damaged_t, mask_t):
    outputs=[]; weights=[]
    with torch.no_grad():
        lama_t = lama_inpaint_batch(damaged_t, mask_t)
        outputs.append(lama_t); weights.append(1.5)

        if loaded.get('gen_best'):
            o = gen_best(damaged_t, mask_t).clamp(-1,1)
            outputs.append(o); weights.append(1.5)

        if loaded.get('gen_ep60'):
            o = gen_ep60(damaged_t, mask_t).clamp(-1,1)
            outputs.append(o); weights.append(1.0)

        if loaded.get('gen_best') and loaded.get('ref_net'):
            coarse = gen_best(damaged_t, mask_t).clamp(-1,1)
            o = ref_net(coarse, damaged_t, mask_t).clamp(-1,1)
            outputs.append(o); weights.append(1.0)

        if loaded.get('old_dun'):
            o = old_dun(lama_t, damaged_t, mask_t).clamp(-1,1)
            outputs.append(o); weights.append(1.0)

        if loaded.get('new_ref'):
            o = new_ref(lama_t, damaged_t, mask_t).clamp(-1,1)
            outputs.append(o); weights.append(4.0)

    fused = sum(o*w for o,w in zip(outputs,weights)) / sum(weights)
    hole  = 1 - mask_t
    return (damaged_t*mask_t + fused.clamp(-1,1)*hole)

# ══════════════════════════════════════════════════════════
# SUMMARY
# ══════════════════════════════════════════════════════════
active = [k for k,v in loaded.items() if v]
wmap   = {'gen_best':1.5,'gen_ep60':1.0,'ref_net':1.0,
          'old_dun':1.0,'new_ref':4.0}
print(f"\n{'='*55}")
print(f"✅ Ensemble ready — {len(active)+1} models active")
print(f"   {'LaMa':<25} weight=1.5  (always)")
for k in active:
    print(f"   {k:<25} weight={wmap.get(k,1.0)}")
print(f"{'='*55}")
print("\n✅ CELL 5b-LOAD DONE — run Cell 5")

# # ============================================================
# # CELL 5: Interface — Full Ensemble Restoration (UPDATED)
# # Uses Cell 6 style mask generation
# # ============================================================

# import numpy as np, cv2, torch
# import torchvision.transforms as T
# import ipywidgets as widgets
# from IPython.display import display, clear_output
# from PIL import Image
# from io import BytesIO
# import matplotlib.pyplot as plt

# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# BG='#0d0a08'; GOLD='#c4924a'; CREAM='#e8d5b0'
# RED='#8b2020'; GREEN='#2d6a2d'

# plt.rcParams.update({
#     'figure.facecolor':BG,
#     'axes.facecolor':BG,
#     'text.color':CREAM
# })

# img_tf = T.Compose([
#     T.ToTensor(),
#     T.Normalize([0.5]*3,[0.5]*3)
# ])

# def unnorm(t):
#     return (t*0.5+0.5).clamp(0,1)

# # ============================================================
# # ✅ MASK — CELL 6 STYLE
# # ============================================================
# def make_mask(pil_img):
#     gray = np.array(pil_img.convert('L'))

#     # Same logic as Cell 6
#     mask255 = (gray > 128).astype(np.uint8) * 255

#     H, W = gray.shape
#     cov = mask255.sum() / (H * W * 255) * 100

#     return mask255, cov

# # ============================================================
# # RESTORE PIPELINE (same as your working code)
# # ============================================================
# def restore(pil_img, mask255):

#     W, H = pil_img.size
#     orig_np = np.array(pil_img.convert('RGB'))

#     # Stage 1 — LaMa
#     mask_pil = Image.fromarray(mask255).convert('L')
#     lama_out = simple_lama(pil_img, mask_pil)
#     lama_np  = np.array(lama_out)

#     # Stage 2 — Ensemble
#     lama_256 = lama_out.resize((256,256))
#     orig_256 = pil_img.resize((256,256))
#     mk_256   = cv2.resize(mask255,(256,256),interpolation=cv2.INTER_NEAREST)

#     lama_t = img_tf(lama_256).unsqueeze(0).to(device)
#     orig_t = img_tf(orig_256).unsqueeze(0).to(device)

#     msk_t  = torch.from_numpy(
#         (mk_256 < 128).astype(np.float32)
#     ).unsqueeze(0).unsqueeze(0).to(device)

#     with torch.no_grad():
#         fused_t = ensemble_restore(orig_t, msk_t)

#     fused_np = unnorm(fused_t).cpu().squeeze(0).permute(1,2,0).numpy()
#     fused_np = (fused_np * 255).astype(np.uint8)

#     fused_full = np.array(
#         Image.fromarray(fused_np).resize((W,H))
#     )

#     # Stage 3 — Blend (same as Cell 6)
#     mask_f = mask255.astype(np.float32)/255.0
#     mask_f = cv2.GaussianBlur(mask_f,(31,31),0)[:,:,None]

#     result = (orig_np*(1-mask_f) + fused_full*mask_f).astype(np.uint8)

#     return Image.fromarray(result)

# # ============================================================
# # METRICS
# # ============================================================
# def compute_metrics(orig, result, mask255):
#     o = np.array(orig.resize((256,256))).astype(np.float32)/255.
#     r = np.array(result.resize((256,256))).astype(np.float32)/255.
#     m = cv2.resize(mask255,(256,256))/255.

#     m = m[:,:,None]

#     mse  = np.mean((r-o)**2*m)+1e-10
#     psnr = 10*np.log10(1./mse)
#     l1   = np.mean(np.abs(r-o)*m)
#     cov  = m.mean()*100

#     return psnr, l1, cov

# # ============================================================
# # DISPLAY
# # ============================================================
# def show_all(orig, result, mask):
#     fig = plt.figure(figsize=(16,5))

#     imgs = [
#         (orig, "INPUT", None),
#         (mask, "MASK", "gray"),
#         (result, "RESTORED", None)
#     ]

#     for i,(img,title,cmap) in enumerate(imgs):
#         ax = fig.add_subplot(1,3,i+1)
#         ax.imshow(img, cmap=cmap)
#         ax.set_title(title, color=GOLD)
#         ax.axis('off')

#     plt.show()

# # ============================================================
# # WIDGETS
# # ============================================================
# state = {"img":None,"mask":None,"res":None}

# upload = widgets.FileUpload(accept='image/*', multiple=False)
# btn_detect = widgets.Button(description="Detect")
# btn_restore = widgets.Button(description="Restore")
# btn_save = widgets.Button(description="Save")

# out = widgets.Output()

# # ============================================================
# # EVENTS
# # ============================================================
# def on_upload(change):
#     if not upload.value:
#         return

#     data = list(upload.value.values())[0]
#     content = data['content']

#     img = Image.open(BytesIO(content)).convert('RGB')
#     state["img"] = img

#     with out:
#         clear_output()
#         plt.imshow(img)
#         plt.title("Uploaded Image")
#         plt.axis('off')
#         plt.show()

# upload.observe(on_upload, names='value')

# def on_detect(b):
#     if state["img"] is None:
#         return

#     mask, cov = make_mask(state["img"])
#     state["mask"] = mask

#     with out:
#         clear_output()
#         print(f"Mask Coverage: {cov:.2f}%")
#         show_all(state["img"], mask, mask)

# btn_detect.on_click(on_detect)

# def on_restore(b):
#     if state["img"] is None or state["mask"] is None:
#         return

#     res = restore(state["img"], state["mask"])
#     state["res"] = res

#     psnr,l1,cov = compute_metrics(state["img"], res, state["mask"])

#     with out:
#         clear_output()
#         print(f"PSNR: {psnr:.2f} | L1: {l1:.4f} | Coverage: {cov:.2f}%")
#         show_all(state["img"], res, state["mask"])

# btn_restore.on_click(on_restore)

# def on_save(b):
#     if state["res"] is None:
#         return
#     state["res"].save("output.png")
#     print("Saved as output.png")

# btn_save.on_click(on_save)

# # ============================================================
# # UI
# # ============================================================
# ui = widgets.VBox([
#     widgets.HBox([upload, btn_detect, btn_restore, btn_save]),
#     out
# ])

# display(ui)

# # ============================================================
# # FINAL CELL 5 — INTERFACE (MATCHES CELL 6)
# # ============================================================

# import numpy as np, cv2, torch
# import torchvision.transforms as T
# import ipywidgets as widgets
# from IPython.display import display, clear_output
# from PIL import Image
# from io import BytesIO
# import matplotlib.pyplot as plt

# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# # ────────────────────────────────────────────────────────────
# # TRANSFORMS
# # ────────────────────────────────────────────────────────────
# img_tf = T.Compose([
#     T.ToTensor(),
#     T.Normalize([0.5]*3,[0.5]*3)
# ])

# def unnorm(t):
#     return (t*0.5+0.5).clamp(0,1)

# # ────────────────────────────────────────────────────────────
# # ✅ SMART MASK (FIXED)
# # ────────────────────────────────────────────────────────────
# def make_mask(pil_img):

#     img  = np.array(pil_img.convert('RGB'))
#     gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

#     # detect damage (bright + dark)
#     bright = (gray > 200)
#     dark   = (gray < 60)

#     mask = (bright | dark).astype(np.uint8) * 255

#     # clean mask
#     k = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))
#     mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, k)
#     mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, k)

#     # 🔥 fallback (prevents empty mask)
#     if mask.sum() == 0:
#         edges = cv2.Canny(gray, 50, 150)
#         mask = (edges > 0).astype(np.uint8) * 255

#     H,W = gray.shape
#     cov = mask.sum()/(H*W*255)*100

#     return mask, cov

# # ────────────────────────────────────────────────────────────
# # ✅ RESTORE (SAME AS CELL 6)
# # ────────────────────────────────────────────────────────────
# def restore(pil_img, mask255):

#     W,H = pil_img.size
#     orig_np = np.array(pil_img.convert('RGB')).astype(np.float32)

#     # ── Stage 1: LaMa ─────────────────────
#     mask_pil = Image.fromarray(mask255).convert('L')
#     lama_out = simple_lama(pil_img, mask_pil)
#     lama_np  = np.array(lama_out).astype(np.float32)

#     # ── Stage 2: Ensemble ────────────────
#     lama_256 = lama_out.resize((256,256), Image.LANCZOS)
#     orig_256 = pil_img.resize((256,256), Image.LANCZOS)
#     mk_256   = cv2.resize(mask255,(256,256),
#                           interpolation=cv2.INTER_NEAREST)

#     lama_t = img_tf(lama_256).unsqueeze(0).to(device)
#     orig_t = img_tf(orig_256).unsqueeze(0).to(device)

#     msk_t = torch.from_numpy(
#         (mk_256 < 128).astype(np.float32)
#     ).unsqueeze(0).unsqueeze(0).to(device)

#     with torch.no_grad():
#         fused_t = ensemble_restore(orig_t, msk_t)

#     fused_np = unnorm(fused_t).cpu().squeeze(0).permute(1,2,0).numpy()
#     fused_np = (fused_np*255).astype(np.uint8)

#     fused_full = np.array(
#         Image.fromarray(fused_np).resize((W,H), Image.LANCZOS)
#     ).astype(np.float32)

#     # ── Stage 3: Fusion ──────────────────
#     combined = (lama_np*0.6 + fused_full*0.4)

#     # ── Stage 4: Feather blending ────────
#     mask_f = mask255.astype(np.float32)/255.0
#     mask_f = cv2.GaussianBlur(mask_f,(31,31),0)[:,:,None]

#     result = (orig_np*(1-mask_f) + combined*mask_f).clip(0,255)

#     return Image.fromarray(result.astype(np.uint8))

# # ────────────────────────────────────────────────────────────
# # METRICS
# # ────────────────────────────────────────────────────────────
# def compute_metrics(orig, result, mask255):
#     o = np.array(orig.resize((256,256))).astype(np.float32)/255.
#     r = np.array(result.resize((256,256))).astype(np.float32)/255.
#     m = cv2.resize(mask255,(256,256))/255.
#     m = m[:,:,None]

#     mse  = np.mean((r-o)**2*m)+1e-10
#     psnr = 10*np.log10(1./mse)
#     l1   = np.mean(np.abs(r-o)*m)
#     cov  = m.mean()*100

#     return psnr, l1, cov

# # ────────────────────────────────────────────────────────────
# # DISPLAY (FIXED ORDER)
# # ────────────────────────────────────────────────────────────
# def show_all(orig, mask, result):

#     fig = plt.figure(figsize=(18,5))

#     ax1 = fig.add_subplot(1,3,1)
#     ax1.imshow(orig)
#     ax1.set_title("INPUT")
#     ax1.axis('off')

#     ax2 = fig.add_subplot(1,3,2)
#     ax2.imshow(mask, cmap='gray')
#     ax2.set_title("MASK")
#     ax2.axis('off')

#     ax3 = fig.add_subplot(1,3,3)
#     ax3.imshow(result)
#     ax3.set_title("RESTORED")
#     ax3.axis('off')

#     plt.show()

# # ────────────────────────────────────────────────────────────
# # UI
# # ────────────────────────────────────────────────────────────
# state = {"img":None,"mask":None,"res":None}

# upload = widgets.FileUpload(accept='image/*', multiple=False)
# btn_detect = widgets.Button(description="Detect")
# btn_restore = widgets.Button(description="Restore")
# btn_save = widgets.Button(description="Save")

# out = widgets.Output()

# # Upload
# def on_upload(change):
#     if not upload.value: return
#     data = list(upload.value.values())[0]
#     img = Image.open(BytesIO(data['content'])).convert('RGB')
#     state["img"] = img

#     with out:
#         clear_output()
#         plt.imshow(img)
#         plt.title("INPUT IMAGE")
#         plt.axis('off')
#         plt.show()

# upload.observe(on_upload, names='value')

# # Detect
# def on_detect(b):
#     mask,cov = make_mask(state["img"])
#     state["mask"] = mask

#     with out:
#         clear_output()
#         print(f"Coverage: {cov:.2f}%")
#         show_all(state["img"], mask, state["img"])

# btn_detect.on_click(on_detect)

# # Restore
# def on_restore(b):
#     res = restore(state["img"], state["mask"])
#     state["res"] = res

#     psnr,l1,cov = compute_metrics(state["img"], res, state["mask"])

#     with out:
#         clear_output()
#         print(f"PSNR:{psnr:.2f}  L1:{l1:.4f}  Coverage:{cov:.2f}%")
#         show_all(state["img"], state["mask"], res)

# btn_restore.on_click(on_restore)

# # Save
# def on_save(b):
#     if state["res"]:
#         state["res"].save("restored.png")
#         print("Saved as restored.png")

# btn_save.on_click(on_save)

# # Layout
# display(widgets.VBox([
#     widgets.HBox([upload, btn_detect, btn_restore, btn_save]),
#     out
# ]))

# # ============================================================
# # FINAL INTERFACE — GOOD MASK + CELL 6 RESTORATION
# # ============================================================

# import numpy as np, cv2, torch
# import torchvision.transforms as T
# import ipywidgets as widgets
# from IPython.display import display, clear_output
# from PIL import Image
# from io import BytesIO
# import matplotlib.pyplot as plt

# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# img_tf = T.Compose([
#     T.ToTensor(),
#     T.Normalize([0.5]*3,[0.5]*3)
# ])

# def unnorm(t):
#     return (t*0.5+0.5).clamp(0,1)

# # ============================================================
# # ✅ FINAL MASK (MATCHES CELL 6 STYLE)
# # ============================================================
# def make_mask(pil_img):

#     img  = np.array(pil_img.convert('RGB'))
#     gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

#     # 1️⃣ Bright white damage
#     bright = gray > 200

#     # 2️⃣ Light faded regions (important for murals)
#     faded = (gray > 150) & (gray < 210)

#     # 3️⃣ Remove texture using blur difference
#     blur = cv2.GaussianBlur(gray, (21,21), 0)
#     texture = np.abs(gray - blur) > 20

#     # Combine intelligently
#     mask = (bright | (faded & texture)).astype(np.uint8) * 255

#     # 🔥 Expand regions (IMPORTANT)
#     kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(11,11))
#     mask = cv2.dilate(mask, kernel, iterations=2)

#     # Smooth edges
#     mask = cv2.GaussianBlur(mask, (9,9), 0)
#     mask = (mask > 80).astype(np.uint8) * 255

#     H,W = gray.shape
#     cov = mask.sum()/(H*W*255)*100

#     return mask, cov

# # ============================================================
# # ✅ RESTORE — EXACT CELL 6 (DO NOT TOUCH)
# # ============================================================
# def restore(pil_img, mask255):

#     W,H = pil_img.size
#     orig_np = np.array(pil_img.convert('RGB')).astype(np.float32)

#     # LaMa
#     mask_pil = Image.fromarray(mask255).convert('L')
#     lama_out = simple_lama(pil_img, mask_pil)
#     lama_np  = np.array(lama_out).astype(np.float32)

#     # Ensemble
#     lama_256 = lama_out.resize((256,256), Image.LANCZOS)
#     orig_256 = pil_img.resize((256,256), Image.LANCZOS)
#     mk_256   = cv2.resize(mask255,(256,256), interpolation=cv2.INTER_NEAREST)

#     lama_t = img_tf(lama_256).unsqueeze(0).to(device)
#     orig_t = img_tf(orig_256).unsqueeze(0).to(device)

#     msk_t = torch.from_numpy(
#         (mk_256 < 128).astype(np.float32)
#     ).unsqueeze(0).unsqueeze(0).to(device)

#     with torch.no_grad():
#         fused_t = ensemble_restore(orig_t, msk_t)

#     fused_np = unnorm(fused_t).cpu().squeeze(0).permute(1,2,0).numpy()
#     fused_np = (fused_np*255).astype(np.uint8)

#     fused_full = np.array(
#         Image.fromarray(fused_np).resize((W,H), Image.LANCZOS)
#     ).astype(np.float32)

#     # SAME AS CELL 6
#     combined = (lama_np*0.6 + fused_full*0.4)

#     mask_f = mask255.astype(np.float32)/255.0
#     mask_f = cv2.GaussianBlur(mask_f,(31,31),0)[:,:,None]

#     result = (orig_np*(1-mask_f) + combined*mask_f).clip(0,255)

#     return Image.fromarray(result.astype(np.uint8))

# # ============================================================
# # DISPLAY
# # ============================================================
# def show_all(orig, mask, result):

#     fig = plt.figure(figsize=(18,5))

#     ax1 = fig.add_subplot(1,3,1)
#     ax1.imshow(orig)
#     ax1.set_title("INPUT")
#     ax1.axis('off')

#     ax2 = fig.add_subplot(1,3,2)
#     ax2.imshow(mask, cmap='gray')
#     ax2.set_title("MASK")
#     ax2.axis('off')

#     ax3 = fig.add_subplot(1,3,3)
#     ax3.imshow(result)
#     ax3.set_title("RESTORED")
#     ax3.axis('off')

#     plt.show()

# # ============================================================
# # UI
# # ============================================================
# state = {"img":None,"mask":None,"res":None}

# upload = widgets.FileUpload(accept='image/*', multiple=False)
# btn_detect = widgets.Button(description="Detect")
# btn_restore = widgets.Button(description="Restore")
# btn_save = widgets.Button(description="Save")

# out = widgets.Output()

# def on_upload(change):
#     if not upload.value: return
#     data = list(upload.value.values())[0]
#     img = Image.open(BytesIO(data['content'])).convert('RGB')
#     state["img"] = img

#     with out:
#         clear_output()
#         plt.imshow(img)
#         plt.title("INPUT IMAGE")
#         plt.axis('off')
#         plt.show()

# upload.observe(on_upload, names='value')

# def on_detect(b):
#     mask,cov = make_mask(state["img"])
#     state["mask"] = mask

#     with out:
#         clear_output()
#         print(f"Coverage: {cov:.2f}%")
#         show_all(state["img"], mask, state["img"])

# btn_detect.on_click(on_detect)

# def on_restore(b):
#     res = restore(state["img"], state["mask"])
#     state["res"] = res

#     with out:
#         clear_output()
#         show_all(state["img"], state["mask"], res)

# btn_restore.on_click(on_restore)

# def on_save(b):
#     if state["res"]:
#         state["res"].save("restored.png")
#         print("Saved as restored.png")

# btn_save.on_click(on_save)

# display(widgets.VBox([
#     widgets.HBox([upload, btn_detect, btn_restore, btn_save]),
#     out
# ]))

# # ============================================================
# # FINAL INTERFACE — STRONG RESTORE + CLEAN DISPLAY MASK
# # ============================================================

# import numpy as np, cv2, torch
# import torchvision.transforms as T
# import ipywidgets as widgets
# from IPython.display import display, clear_output
# from PIL import Image
# from io import BytesIO
# import matplotlib.pyplot as plt

# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# # ────────────────────────────────────────────────────────────
# # TRANSFORMS
# # ────────────────────────────────────────────────────────────
# img_tf = T.Compose([
#     T.ToTensor(),
#     T.Normalize([0.5]*3,[0.5]*3)
# ])

# def unnorm(t):
#     return (t*0.5+0.5).clamp(0,1)

# # ============================================================
# # 🔥 DUAL MASK SYSTEM
# # ============================================================
# def make_mask(pil_img):

#     img  = np.array(pil_img.convert('RGB'))
#     gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

#     # ------------------------------------------------------
#     # 🔥 STRONG MASK (USED FOR RESTORATION)
#     # ------------------------------------------------------
#     bright = gray > 200
#     faded  = (gray > 150) & (gray < 210)

#     blur = cv2.GaussianBlur(gray, (21,21), 0)
#     texture = np.abs(gray - blur) > 20

#     mask_restore = (bright | (faded & texture)).astype(np.uint8) * 255

#     kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(11,11))
#     mask_restore = cv2.dilate(mask_restore, kernel, iterations=2)

#     mask_restore = cv2.GaussianBlur(mask_restore, (9,9), 0)
#     mask_restore = (mask_restore > 80).astype(np.uint8) * 255

#     # ------------------------------------------------------
#     # ✅ CLEAN MASK (USED ONLY FOR DISPLAY)
#     # ------------------------------------------------------
#     bright_d = (gray > 200)
#     dark_d   = (gray < 60)

#     mask_display = (bright_d | dark_d).astype(np.uint8) * 255

#     k = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))
#     mask_display = cv2.morphologyEx(mask_display, cv2.MORPH_OPEN, k)
#     mask_display = cv2.morphologyEx(mask_display, cv2.MORPH_CLOSE, k)

#     if mask_display.sum() == 0:
#         edges = cv2.Canny(gray, 50, 150)
#         mask_display = (edges > 0).astype(np.uint8) * 255

#     H,W = gray.shape
#     cov = mask_restore.sum()/(H*W*255)*100

#     return mask_restore, mask_display, cov

# # ============================================================
# # ✅ RESTORE — EXACT CELL 6
# # ============================================================
# def restore(pil_img, mask255):

#     W,H = pil_img.size
#     orig_np = np.array(pil_img.convert('RGB')).astype(np.float32)

#     # LaMa
#     mask_pil = Image.fromarray(mask255).convert('L')
#     lama_out = simple_lama(pil_img, mask_pil)
#     lama_np  = np.array(lama_out).astype(np.float32)

#     # Ensemble
#     lama_256 = lama_out.resize((256,256), Image.LANCZOS)
#     orig_256 = pil_img.resize((256,256), Image.LANCZOS)
#     mk_256   = cv2.resize(mask255,(256,256),
#                           interpolation=cv2.INTER_NEAREST)

#     lama_t = img_tf(lama_256).unsqueeze(0).to(device)
#     orig_t = img_tf(orig_256).unsqueeze(0).to(device)

#     msk_t = torch.from_numpy(
#         (mk_256 < 128).astype(np.float32)
#     ).unsqueeze(0).unsqueeze(0).to(device)

#     with torch.no_grad():
#         fused_t = ensemble_restore(orig_t, msk_t)

#     fused_np = unnorm(fused_t).cpu().squeeze(0).permute(1,2,0).numpy()
#     fused_np = (fused_np*255).astype(np.uint8)

#     fused_full = np.array(
#         Image.fromarray(fused_np).resize((W,H), Image.LANCZOS)
#     ).astype(np.float32)

#     # SAME AS CELL 6
#     combined = (lama_np*0.6 + fused_full*0.4)

#     mask_f = mask255.astype(np.float32)/255.0
#     mask_f = cv2.GaussianBlur(mask_f,(31,31),0)[:,:,None]

#     result = (orig_np*(1-mask_f) + combined*mask_f).clip(0,255)

#     return Image.fromarray(result.astype(np.uint8))

# # ============================================================
# # DISPLAY
# # ============================================================
# def show_all(orig, mask_display, result):

#     fig = plt.figure(figsize=(18,5))

#     ax1 = fig.add_subplot(1,3,1)
#     ax1.imshow(orig)
#     ax1.set_title("INPUT")
#     ax1.axis('off')

#     ax2 = fig.add_subplot(1,3,2)
#     ax2.imshow(mask_display, cmap='gray')
#     ax2.set_title("MASK (CLEAN)")
#     ax2.axis('off')

#     ax3 = fig.add_subplot(1,3,3)
#     ax3.imshow(result)
#     ax3.set_title("RESTORED")
#     ax3.axis('off')

#     plt.show()

# # ============================================================
# # UI
# # ============================================================
# state = {"img":None,"mask_restore":None,"mask_display":None,"res":None}

# upload = widgets.FileUpload(accept='image/*', multiple=False)
# btn_detect = widgets.Button(description="Detect")
# btn_restore = widgets.Button(description="Restore")
# btn_save = widgets.Button(description="Save")

# out = widgets.Output()

# def on_upload(change):
#     if not upload.value: return
#     data = list(upload.value.values())[0]
#     img = Image.open(BytesIO(data['content'])).convert('RGB')
#     state["img"] = img

#     with out:
#         clear_output()
#         plt.imshow(img)
#         plt.title("INPUT IMAGE")
#         plt.axis('off')
#         plt.show()

# upload.observe(on_upload, names='value')

# def on_detect(b):
#     m_res, m_disp, cov = make_mask(state["img"])
#     state["mask_restore"] = m_res
#     state["mask_display"] = m_disp

#     with out:
#         clear_output()
#         print(f"Coverage: {cov:.2f}%")
#         show_all(state["img"], m_disp, state["img"])

# btn_detect.on_click(on_detect)

# def on_restore(b):
#     res = restore(state["img"], state["mask_restore"])
#     state["res"] = res

#     with out:
#         clear_output()
#         show_all(state["img"], state["mask_display"], res)

# btn_restore.on_click(on_restore)

# def on_save(b):
#     if state["res"]:
#         state["res"].save("restored.png")
#         print("Saved as restored.png")

# btn_save.on_click(on_save)

# display(widgets.VBox([
#     widgets.HBox([upload, btn_detect, btn_restore, btn_save]),
#     out
# ]))

# ============================================================
# FINAL INTERFACE — COMPLETE (MASK + RESTORE + METRICS)
# ============================================================

import numpy as np, cv2, torch
import torchvision.transforms as T
import ipywidgets as widgets
from IPython.display import display, clear_output
from PIL import Image
from io import BytesIO
import matplotlib.pyplot as plt

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# ────────────────────────────────────────────────────────────
# TRANSFORMS
# ────────────────────────────────────────────────────────────
img_tf = T.Compose([
    T.ToTensor(),
    T.Normalize([0.5]*3,[0.5]*3)
])

def unnorm(t):
    return (t*0.5+0.5).clamp(0,1)

# ============================================================
# SSIM
# ============================================================
def ssim_np(a, b):
    C1, C2 = 0.01**2, 0.03**2
    a = a.astype(np.float64)
    b = b.astype(np.float64)

    mu_a = cv2.GaussianBlur(a, (11,11), 1.5)
    mu_b = cv2.GaussianBlur(b, (11,11), 1.5)

    mu_a2 = mu_a**2
    mu_b2 = mu_b**2
    mu_ab = mu_a * mu_b

    sigma_a = cv2.GaussianBlur(a*a,(11,11),1.5) - mu_a2
    sigma_b = cv2.GaussianBlur(b*b,(11,11),1.5) - mu_b2
    sigma_ab= cv2.GaussianBlur(a*b,(11,11),1.5) - mu_ab

    ssim_map = ((2*mu_ab + C1)*(2*sigma_ab + C2)) / \
               ((mu_a2 + mu_b2 + C1)*(sigma_a + sigma_b + C2))

    return float(ssim_map.mean())

# ============================================================
# DUAL MASK
# ============================================================
def make_mask(pil_img):

    img  = np.array(pil_img.convert('RGB'))
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    # --- STRONG MASK (RESTORE) ---
    bright = gray > 200
    faded  = (gray > 150) & (gray < 210)

    blur = cv2.GaussianBlur(gray, (21,21), 0)
    texture = np.abs(gray - blur) > 20

    mask_restore = (bright | (faded & texture)).astype(np.uint8) * 255

    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(11,11))
    mask_restore = cv2.dilate(mask_restore, kernel, iterations=2)

    mask_restore = cv2.GaussianBlur(mask_restore, (9,9), 0)
    mask_restore = (mask_restore > 80).astype(np.uint8) * 255

    # --- CLEAN MASK (DISPLAY) ---
    bright_d = (gray > 200)
    dark_d   = (gray < 60)

    mask_display = (bright_d | dark_d).astype(np.uint8) * 255

    k = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))
    mask_display = cv2.morphologyEx(mask_display, cv2.MORPH_OPEN, k)
    mask_display = cv2.morphologyEx(mask_display, cv2.MORPH_CLOSE, k)

    if mask_display.sum() == 0:
        edges = cv2.Canny(gray, 50, 150)
        mask_display = (edges > 0).astype(np.uint8) * 255

    H,W = gray.shape
    cov_restore = mask_restore.sum()/(H*W*255)*100
    cov_display = mask_display.sum()/(H*W*255)*100

    return mask_restore, mask_display, cov_restore, cov_display

# ============================================================
# RESTORE (CELL 6 EXACT)
# ============================================================
def restore(pil_img, mask255):

    W,H = pil_img.size
    orig_np = np.array(pil_img.convert('RGB')).astype(np.float32)

    mask_pil = Image.fromarray(mask255).convert('L')
    lama_out = simple_lama(pil_img, mask_pil)
    lama_np  = np.array(lama_out).astype(np.float32)

    lama_256 = lama_out.resize((256,256), Image.LANCZOS)
    orig_256 = pil_img.resize((256,256), Image.LANCZOS)
    mk_256   = cv2.resize(mask255,(256,256), interpolation=cv2.INTER_NEAREST)

    lama_t = img_tf(lama_256).unsqueeze(0).to(device)
    orig_t = img_tf(orig_256).unsqueeze(0).to(device)

    msk_t = torch.from_numpy(
        (mk_256 < 128).astype(np.float32)
    ).unsqueeze(0).unsqueeze(0).to(device)

    with torch.no_grad():
        fused_t = ensemble_restore(orig_t, msk_t)

    fused_np = unnorm(fused_t).cpu().squeeze(0).permute(1,2,0).numpy()
    fused_np = (fused_np*255).astype(np.uint8)

    fused_full = np.array(
        Image.fromarray(fused_np).resize((W,H), Image.LANCZOS)
    ).astype(np.float32)

    combined = (lama_np*0.6 + fused_full*0.4)

    mask_f = mask255.astype(np.float32)/255.0
    mask_f = cv2.GaussianBlur(mask_f,(31,31),0)[:,:,None]

    result = (orig_np*(1-mask_f) + combined*mask_f).clip(0,255)

    return Image.fromarray(result.astype(np.uint8))

# ============================================================
# DISPLAY
# ============================================================
def show_all(orig, mask_display, result):

    fig = plt.figure(figsize=(18,5))

    ax1 = fig.add_subplot(1,3,1)
    ax1.imshow(orig)
    ax1.set_title("INPUT")
    ax1.axis('off')

    ax2 = fig.add_subplot(1,3,2)
    ax2.imshow(mask_display, cmap='gray')
    ax2.set_title("MASK (CLEAN)")
    ax2.axis('off')

    ax3 = fig.add_subplot(1,3,3)
    ax3.imshow(result)
    ax3.set_title("RESTORED")
    ax3.axis('off')

    plt.show()

# ============================================================
# UI
# ============================================================
state = {"img":None,"mask_restore":None,"mask_display":None,"res":None}

upload = widgets.FileUpload(accept='image/*', multiple=False)
btn_detect = widgets.Button(description="Detect")
btn_restore = widgets.Button(description="Restore")
btn_save = widgets.Button(description="Save")

out = widgets.Output()

def on_upload(change):
    if not upload.value: return
    data = list(upload.value.values())[0]
    img = Image.open(BytesIO(data['content'])).convert('RGB')
    state["img"] = img

    with out:
        clear_output()
        plt.imshow(img)
        plt.title("INPUT IMAGE")
        plt.axis('off')
        plt.show()

upload.observe(on_upload, names='value')

def on_detect(b):
    m_res, m_disp, cov_r, cov_d = make_mask(state["img"])
    state["mask_restore"] = m_res
    state["mask_display"] = m_disp

    with out:
        clear_output()
        print(f"Coverage (Display Mask): {cov_d:.2f}%")
        show_all(state["img"], m_disp, state["img"])

btn_detect.on_click(on_detect)

def on_restore(b):
    res = restore(state["img"], state["mask_restore"])
    state["res"] = res

    # --- resize ---
    orig = np.array(state["img"].resize((256,256))).astype(np.float32)/255.
    outp = np.array(res.resize((256,256))).astype(np.float32)/255.

    # ✅ USE DISPLAY MASK FOR METRICS
    mask = cv2.resize(state["mask_display"], (256,256))/255.
    mask = mask[:,:,None]

    # --- metrics ---
    mse = np.mean((orig - outp)**2 * mask) + 1e-10
    psnr = 10*np.log10(1./mse)

    l1 = np.mean(np.abs(orig - outp) * mask)

    # 🔥 SSIM ALSO BASED ON DISPLAY MASK REGION
    # apply mask before SSIM
    orig_masked = orig * mask
    outp_masked = outp * mask

    ssim = ssim_np(orig_masked, outp_masked)

    cov = mask.mean()*100

    with out:
        clear_output()
        print(f"PSNR: {psnr:.2f} dB")
        print(f"SSIM (Display Mask): {ssim:.4f}")
        print(f"L1:   {l1:.4f}")
        print(f"Coverage (Display): {cov:.2f}%")

        show_all(state["img"], state["mask_display"], res)

btn_restore.on_click(on_restore)

def on_save(b):
    if state["res"]:
        state["res"].save("restored.png")
        print("Saved as restored.png")

btn_save.on_click(on_save)

display(widgets.VBox([
    widgets.HBox([upload, btn_detect, btn_restore, btn_save]),
    out
]))

import gradio as gr
import numpy as np, cv2, torch
from PIL import Image
import torchvision.transforms as T

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# ---------------- TRANSFORMS ----------------
img_tf = T.Compose([
    T.ToTensor(),
    T.Normalize([0.5]*3,[0.5]*3)
])

def unnorm(t):
    return (t*0.5+0.5).clamp(0,1)

# ---------------- SSIM ----------------
def ssim_np(a, b):
    C1, C2 = 0.01**2, 0.03**2
    a = a.astype(np.float64)
    b = b.astype(np.float64)

    mu_a = cv2.GaussianBlur(a,(11,11),1.5)
    mu_b = cv2.GaussianBlur(b,(11,11),1.5)

    mu_a2 = mu_a**2
    mu_b2 = mu_b**2
    mu_ab = mu_a * mu_b

    sigma_a = cv2.GaussianBlur(a*a,(11,11),1.5) - mu_a2
    sigma_b = cv2.GaussianBlur(b*b,(11,11),1.5) - mu_b2
    sigma_ab= cv2.GaussianBlur(a*b,(11,11),1.5) - mu_ab

    ssim_map = ((2*mu_ab + C1)*(2*sigma_ab + C2)) / \
               ((mu_a2 + mu_b2 + C1)*(sigma_a + sigma_b + C2))

    return float(ssim_map.mean())

# ---------------- MASK ----------------
def make_mask(pil_img):
    img = np.array(pil_img.convert('RGB'))
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    bright = gray > 200
    faded  = (gray > 150) & (gray < 210)

    blur = cv2.GaussianBlur(gray,(21,21),0)
    texture = np.abs(gray - blur) > 20

    mask_restore = (bright | (faded & texture)).astype(np.uint8)*255

    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(11,11))
    mask_restore = cv2.dilate(mask_restore,kernel,2)

    mask_restore = cv2.GaussianBlur(mask_restore,(9,9),0)
    mask_restore = (mask_restore>80).astype(np.uint8)*255

    mask_display = ((gray>200)|(gray<60)).astype(np.uint8)*255

    return mask_restore, mask_display

# ---------------- RESTORE ----------------
def restore(pil_img, mask255):

    W,H = pil_img.size
    orig_np = np.array(pil_img).astype(np.float32)

    mask_pil = Image.fromarray(mask255).convert('L')
    lama_out = simple_lama(pil_img, mask_pil)
    lama_np  = np.array(lama_out).astype(np.float32)

    lama_256 = lama_out.resize((256,256))
    orig_256 = pil_img.resize((256,256))
    mk_256   = cv2.resize(mask255,(256,256))

    lama_t = img_tf(lama_256).unsqueeze(0).to(device)
    orig_t = img_tf(orig_256).unsqueeze(0).to(device)

    msk_t = torch.from_numpy((mk_256<128).astype(np.float32)).unsqueeze(0).unsqueeze(0).to(device)

    with torch.no_grad():
        fused_t = ensemble_restore(orig_t, msk_t)

    fused_np = unnorm(fused_t).cpu().squeeze().permute(1,2,0).numpy()
    fused_np = (fused_np*255).astype(np.uint8)

    fused_full = np.array(Image.fromarray(fused_np).resize((W,H))).astype(np.float32)

    combined = lama_np*0.6 + fused_full*0.4

    mask_f = mask255.astype(np.float32)/255.0
    mask_f = cv2.GaussianBlur(mask_f,(31,31),0)[:,:,None]

    result = (orig_np*(1-mask_f) + combined*mask_f).astype(np.uint8)

    return result

# ---------------- PROCESS ----------------
def process(img):
    if img is None:
        return None, None, None, "Upload image first"

    pil_img = Image.fromarray(img.astype(np.uint8))
    mask_restore, mask_display = make_mask(pil_img)
    result = restore(pil_img, mask_restore)

    orig = cv2.resize(np.array(pil_img),(256,256))/255.
    outp = cv2.resize(result,(256,256))/255.

    mask = cv2.resize(mask_display,(256,256))/255.
    mask = mask[:,:,None]

    mse = np.mean((orig-outp)**2 * mask) + 1e-10
    psnr = 10*np.log10(1./mse)
    l1 = np.mean(np.abs(orig-outp)*mask)
    ssim = ssim_np(orig*mask, outp*mask)

    metrics = f"""
### 📊 Metrics
- PSNR: {psnr:.2f} dB
- SSIM: {ssim:.4f}
- L1: {l1:.4f}
"""

    return img, mask_display, result, metrics

# ================= UI =================
with gr.Blocks(css="""
body {margin:0; background:black;}

.hero {
    height: 83vh;
    background: linear-gradient(rgba(139,32,32,0.7), rgba(0,0,0,0.9)),
                url('https://images.unsplash.com/photo-1501785888041-af3ef285b470');
    background-size:cover;
    display:flex;
    justify-content:center;
    align-items:center;
    flex-direction:column;
    color:white;
}

.title {font-size:50px; font-weight:bold;}

.enter-btn {
    margin-top:20px;
    padding:12px 30px;
    font-size:18px;
    background:#c4924a;
    color:black;
}

.panel {
    background: rgba(0,0,0,0.6);
    border-radius:15px;
    padding:20px;
    margin:10px;
}
""") as demo:

    # -------- LANDING --------
    with gr.Column(visible=True) as landing:
        gr.HTML("<div class='hero'><div class='title'>Ancient Echoes<br>AI Restoration</div></div>")
        enter = gr.Button("Enter →", elem_classes="enter-btn")

    # -------- APP --------
    with gr.Column(visible=False) as app:

        with gr.Row():
            with gr.Column(scale=2, elem_classes="panel"):
                input_img = gr.Image(label="Upload Image")
                btn = gr.Button("Restore")

            with gr.Column(scale=1, elem_classes="panel"):
                metrics = gr.Markdown("Metrics will appear here")

        with gr.Row():
            input_preview = gr.Image(label="Input")
            mask_img = gr.Image(label="Mask")
            result_img = gr.Image(label="Restored")

    # -------- NAV --------
    def go():
        return gr.update(visible=False), gr.update(visible=True)

    enter.click(go, outputs=[landing, app])

    btn.click(process,
              inputs=input_img,
              outputs=[input_preview, mask_img, result_img, metrics])

demo.launch(share=True)